{{- if .Values.service.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.service.domain }}
    - notify-messenger-notify-server-staging.lavanote.com
    secretName: {{ .Values.application.name }}-tls
  rules:
  - host: {{ template "hostname" .Values.service.url }}
    http:
      paths:
      - path: /app
        backend:
          serviceName: {{ .Values.application.name }}
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
