// DO NOT EDIT THIS FILE.
// It is replaced by an auto-generated version at compile-time

/**
 * Has this build-info.ts been autogenerated. Used to detect
 * at runtime whether a real build-info.ts was injected.
 */
export const BUILD_INFO_REAL = false;

/**
 * The internal release name. Currently, this is the commit SHA of the build.
 * Used by Sentry's error handler to match code versions to source maps.
 */
export const RELEASE_NAME = '[unknown release name]';

/**
 * A string such as 'Wed Jan 23 12:55:37 EST 2019' (output from /bin/date) indicating when this build was built.
 */
export const BUILD_DATE = '[unknown build date]';
